---
title: "Oak Data Exploration"
format: html
editor: visual
---

## Oak Exploratory data analysis and cleaning

```{r}
#install.packages("tidyverse")
#install.packages("plyr")


library(tidyverse)
library(plyr)
library(dplyr)
library(readxl)
Survival_HeightApril26Blocks7_6Clean <- 
  read_excel("Oak Project/Data/Survival_HeightApril26Blocks7&6Clean.xlsx", 
                                                   sheet = "Input1", skip = 1)
View(Survival_HeightApril26Blocks7_6Clean)

names(Survival_HeightApril26Blocks7_6Clean)



oak_data <- list.files(path = "~/GitHub/AdvancedQuantF26/Oak Project/Data",
                       pattern = "*6Clean.xlsx",
                       full.names = TRUE) |> 
lapply(read_excel,
       na = "NA", sheet = "Input1",
       skip = 1) |> 
  bind_rows()
```

```{r}

oak_data <-
  oak_data |> 
  dplyr::rename(Page_Num = "Page #",
         Date = "MM/DD/YYYY",
         Recorder ="Name",
         Block ="#...4",
         Tag_Num = "#...5",
         Oak_Type ="NR, S, or A",
         Treatment ="AC, OA, NP, DT, or DL",
         OA_Microclimate ="TH, TI, CN",
         Seedling_Height ="(cm)",
         Leaves_Num ="#...10",
         Dead_Leaves_Num ="#...11",
         Leaf_Greenness ="%",
         Germination_Num ="#...13",
         RCD ="(mm)",
         Notes  ="as written on data sheet")
```

```{r}
oct_data <- read_excel("Oak Project/Data/Survival_HeightOct2025Clean.xlsx",
                       sheet = 'Input1',
                                                      skip = 1)
oct_data <- oct_data |> 
  dplyr::rename(Page_Num = "Page #",
                Date = "MM/DD/YYYY",
                Recorder = "Code",
                Block ="#...4",
                Tag_Num = "#...5",
                Oak_Type ="NR, S, or A",
                Treatment ="AC, OA, SA, NP, or DT",
                Seedling_Height ="(cm)...8",
                Leaves_Num ="#...9",
                Base_Seedling_Circumference = "(cm)...10",
                Base_Seedling_Diameter = "(mm)",
                Alive_Dead = "Yes, No, or Missing?",
                Notes = "as written on data sheet")

oak_data_full <- full_join(oak_data, oct_data)

```

```{r}
oak_data_full <- 
  oak_data_full |> 
  mutate(Seedling_Height = as.numeric(Seedling_Height))

str(Survival_HeightApril26Blocks7_6Clean)

oak_data_full <- 
  oak_data_full |> 
  mutate(Leaves_Num = as.numeric(Leaves_Num))


oak_data_full <- 
  oak_data_full |> 
  mutate(Dead_Leaves_Num = as.numeric(Dead_Leaves_Num))


oak_data_full <- 
  oak_data_full |> 
  mutate(Leaf_Greenness = as.numeric(Leaf_Greenness))

oak_data_full <- 
  oak_data_full |> 
  mutate(Germination_Num = as.numeric(Germination_Num))

oak_data_full <- 
  oak_data_full |> 
  mutate(RCD = as.numeric(RCD))


oak_data_full <- 
  oak_data_full |> 
  mutate(Base_Seedling_Circumference = as.numeric(Base_Seedling_Circumference))

oak_data_full <- 
  oak_data_full |> 
  mutate(Base_Seedling_Diameter = as.numeric(Base_Seedling_Diameter))

oak_data_full <- oak_data_full |> 
  filter(Page_Num != "NA")




oak_data_clean<- oak_data_full |> 
  separate(Tag_Num, into = c("Tag_Num", "Acorn_Num"), sep = "A") |> 
  mutate(Tag_Num = as.numeric(Tag_Num),
         Acorn_Num = as.numeric(Acorn_Num))


oak_data_clean <- oak_data_clean |>
mutate(Dead = case_when(
  Seedling_Height == 0 ~ "Dead",
Seedling_Height > 0 ~ "Alive"
))

#below dont worry about
         
#Acorn_ID_table <- oak_data_clean |> 
 # select(Tag_Num, Block, Treatment, OA_Microclimate, Date) |> 
  #distinct() |> 
  #arrange(Tag_Num) |> 
  #mutate(Acorn1 = 1, Acorn2 = 2, Acorn3 = 3) |> 
  #pivot_longer(cols = c(Acorn1, Acorn2, Acorn3),
   #            names_to = "Whatever",
    #           values_to = "Acorn_Num") |> 
  #select(-Whatever)

#oak_data_clean |> full_join(Acorn_ID_table)
```

```{r}
#Graph Time!!
oak_data_graph <- oak_data_clean |> 
filter(Seedling_Height != 0) 
  


ggplot(oak_data_graph) +
  aes(x = Seedling_Height) + 
  geom_bar()
#Some of these seedlings appear really high

ggplot(oak_data_graph) +
  aes(x = Leaves_Num) + 
  geom_bar()
#Few data points at 300+ leaves

ggplot(oak_data_graph)+
  aes(x = Leaf_Greenness)+
  geom_bar()

ggplot(oak_data_clean)+
  aes(x = Dead)+
  geom_bar()
#There are a ton of NA's, what does this mean in context to dead or alive?
```

```{r}
#Survival_HeightApril26Blocks7_6Clean <-
 # Survival_HeightApril26Blocks7_6Clean |> 
#  rename(Page_Num = "Page #",
 #        Date = "MM/DD/YYYY",
  #       Recorder ="Name",
   #     Block ="#...4",
    #    Tag_Num = "#...5",
     #   Oak_Type ="NR, S, or A",
      #  Treatment ="AC, OA, NP, DT, or DL",
      #   OA_Microclimate ="TH, TI, CN",
       # Seedling_Height ="(cm)",
      #  Leaves_Num ="#...10",
       # Dead_Leaves_Num ="#...11",
        #Leaf_Greenness ="%",
        #Germination_Num ="#...13",
        #RCD ="(mm)",
       #Notes  ="as written on data sheet")
```

Changing columns to be numeric

```{r}
#str(Survival_HeightApril26Blocks7_6Clean)

#Survival_HeightApril26Blocks7_6Clean <- 
 # Survival_HeightApril26Blocks7_6Clean |> 
  #mutate(Seedling_Height = as.numeric(Seedling_Height))

#str(Survival_HeightApril26Blocks7_6Clean)

#Survival_HeightApril26Blocks7_6Clean <- 
 # Survival_HeightApril26Blocks7_6Clean |> 
  #mutate(Leaves_Num = as.numeric(Leaves_Num))


#Survival_HeightApril26Blocks7_6Clean <- 
 # Survival_HeightApril26Blocks7_6Clean |> 
  #mutate(Dead_Leaves_Num = as.numeric(Dead_Leaves_Num))


#Survival_HeightApril26Blocks7_6Clean <- 
 # Survival_HeightApril26Blocks7_6Clean |> 
  #mutate(Leaf_Greenness = as.numeric(Leaf_Greenness))

#Survival_HeightApril26Blocks7_6Clean <- 
 # Survival_HeightApril26Blocks7_6Clean |> 
  #mutate(Germination_Num = as.numeric(Germination_Num))

#Survival_HeightApril26Blocks7_6Clean <- 
 # Survival_HeightApril26Blocks7_6Clean |> 
  #mutate(RCD = as.numeric(RCD))


#str(Survival_HeightApril26Blocks7_6Clean)


```

Need to separate the tag numbers from the acorn numbers. Will need to create a new column

```{r}

```

Going to check data for any outliers

```{r}
#ggplot(Survival_HeightApril26Blocks7_6Clean) +
 # aes(x = Seedling_Height) + 
  #geom_bar()


#which(Survival_HeightApril26Blocks7_6Clean$Seedling_Height == 60)
#Row 12 is a huge outlier, may consider removing 

#ggplot(Survival_HeightApril26Blocks7_6Clean) +
 # aes(x = RCD) + 
  #geom_bar()
#RCD has a patch at 7.5 that could be removed


```

Going to check on repeat entries

```{r}
#unique(Survival_HeightApril26Blocks7_6Clean$Tag_Num)
#Looks like there are no repeat entries
```

```{r}
 
```
